version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  run_tests:
    docker:
      - image: circleci/node:13
      - image: circleci/postgres
        environment:
          POSTGRES_USER: rm
          POSTGRES_PASSWORD: root
          POSTGRES_DB: gamebible_test

    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm run test:ci
workflows:
  build-and-test:
    jobs:
      - run_tests
